-- Generated by ~/.config/hypr/scripts/theme-picker
return {
  accent = "#5f5f87",
  bg = "#222222",
  fg = "#eeeeee",
  gray2 = "#444444",
  gray3 = "#bbbbbb",
  red = "#cc5555",
  yellow = "#cccc55",
  green = "#55aa55",
}
