background {
    blur_passes = 2
}

label {
    text = $TIME
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    size = 200, 50
    outline_thickness = 2
    position = 0, -100
    halign = center
    valign = center
}
