#!/bin/python

import time
import threading
from pynput.mouse import Listener, Button, Controller

activated = False
mouse = Controller()

def on_click(x, y, key, z):
    global activated
    if key == Button.button9:
        activated = not activated

def doClick():
    global activated
    while True:
        if activated:
            mouse.click(Button.left, 1)
            time.sleep(0.06)


threading.Thread(target = doClick).start()

listner = Listener(on_click=on_click)
listner.start()

input()
