-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- Rice accent sync: generated by ~/.config/hypr/scripts/theme-picker
local function rice_apply_theme()
  local ok, colors = pcall(dofile, vim.fn.expand("~/.config/hypr/themes/nvim.lua"))
  if not ok or type(colors) ~= "table" then
    return
  end
  local set = vim.api.nvim_set_hl
  set(0, "Normal", { bg = colors.bg, fg = colors.gray3 or colors.fg })
  set(0, "NormalFloat", { bg = colors.bg, fg = colors.fg, blend = 0 })
  set(0, "CursorLine", { bg = colors.gray2 })
  set(0, "LineNr", { fg = "#777777" })
  set(0, "CursorLineNr", { fg = colors.fg, bold = true })
  set(0, "Visual", { bg = colors.accent, fg = colors.fg })
  set(0, "Search", { bg = colors.accent, fg = colors.fg })
  set(0, "IncSearch", { bg = colors.accent, fg = colors.fg })
  set(0, "StatusLine", { bg = colors.accent, fg = colors.fg })
  set(0, "WinSeparator", { fg = colors.accent })
  set(0, "PmenuSel", { bg = colors.accent, fg = colors.fg })
  set(0, "Keyword", { fg = colors.accent, bold = true })
  set(0, "Function", { fg = colors.fg })
  set(0, "String", { fg = colors.yellow })
  set(0, "Comment", { fg = "#777777", italic = true })
end

rice_apply_theme()
vim.api.nvim_create_autocmd({ "ColorScheme", "VimEnter" }, {
  group = vim.api.nvim_create_augroup("rice_theme_sync", { clear = true }),
  callback = rice_apply_theme,
})

